server:
  port: 8080
spring:
  config:
    import:
      - nacos:${spring.application.name}.yml
  cloud:
    openfeign:
      client:
        config:
          default:
            logger-level: full
    nacos:
      discovery:
        namespace: cf-best
logging:
  level:
    com.cfbest.server.feign.IpApiFeign: debug